DROP TABLE IF EXISTS waitlist;

CREATE TABLE waitlist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    severity INTEGER NOT NULL,
    description TEXT,
    arrival TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    in_progress INTEGER NOT NULL DEFAULT 0
);